{{- if and .Values.web.enabled .Values.web.ingress.compress }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ template "odoo.web.fullname" . }}-compress
spec:
  compress: {}
{{- end }}
